/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type OpenAIApiKey = string;
export interface Session {
  'owner' : Principal,
  'task' : string,
  'timestamp' : bigint,
  'outcome' : string,
}
export type SessionId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'endSession' : ActorMethod<[SessionId], boolean>,
  'generateFocusTask' : ActorMethod<[string, string, string], string>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSession' : ActorMethod<[SessionId], [] | [Session]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isApiKeyConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startSession' : ActorMethod<[], SessionId>,
  'storeApiKey' : ActorMethod<[OpenAIApiKey], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSessionOutcome' : ActorMethod<[SessionId, string], boolean>,
  'updateSessionTask' : ActorMethod<[SessionId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];